 Name -Kanishika

Roll No. - 102317021




 Assignment-1



a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
print(arr)
arr[:]=arr[::-1]
print(arr)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(arr)
print()
print(arr.flatten())

[[1 2 3]
 [2 4 5]
 [1 2 3]]

[1 2 3 2 4 5 1 2 3]


c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(np.array_equal(arr1, arr2))

True


d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,1,2,1,1,1])
counts=np.bincount(x)
print(counts)
maxi=0
ele=0
for i in range (counts.size):
  if(counts[i]>maxi):
    maxi=counts[i]
    ele=i
print(ele)


y=np.array([1,1,1,2,3,4,2,4,3,3])
counts=np.bincount(y)
print(counts)
maxi=0
ele=0
for i in range (counts.size):
  if(counts[i]>maxi):
    maxi=counts[i]
    ele=i
print(ele)



[0 5 2 1 1 1]
1
[0 3 2 3 2]
1


e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise\

In [ ]:
import numpy as np
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
arr=np.array(gfg)
arr=arr.flatten()
print("The array is : ",arr)
print()
sum=0
for i in arr:
  sum=sum+i
print("sum of all ele is ",sum)
print()
sum=0
i,j=gfg.shape
for ii in range(i):
  for jj in range(j):
    sum=sum+gfg[ii,jj]
  print("sum of row wise ele are : " ,sum)
  sum=0

print()
sum=0
for jj in range(j):
  for ii in range(i):
    sum=sum+gfg[ii,jj]
  print("sum of coloumn wise ele are : " ,sum)
  sum=0

The array is :  [ 4  1  9 12  3  1  4  5  6]

sum of all ele is  45

sum of row wise ele are :  14
sum of row wise ele are :  16
sum of row wise ele are :  15

sum of coloumn wise ele are :  20
sum of coloumn wise ele are :  9
sum of coloumn wise ele are :  16


f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]),
find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [ ]:
import numpy as np
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
i,j=n_array.shape
sum=0
for ii in range (i):
  for jj in range (j):
    if(ii==jj):
      sum=sum+n_array[ii,jj]

print("The sum of diagonal values are: ",sum)
print()
eigenvalues,eigenvectors=np.linalg.eig(n_array)
print("Eigenvalues are:")
print()
print(eigenvalues)
print()
print("Eigenvectors are:")
print()
print(eigenvectors)
print()
inverse=np.linalg.inv(n_array)
print("Inverse of Matrix:")
print()
print(inverse)
print()
det=np.linalg.det(n_array)
print("Determinant:",det)

The sum of diagonal values are:  176

Eigenvalues are:

[98.16835147 28.097044   49.73460452]

Eigenvectors are:

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse of Matrix:

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant: 137180.0000000001


g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]


ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
import numpy as np

p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
mul1=np.dot(p,q)
print("Matrix Multiplication:")
print()
print(mul1)
cov1=np.cov(p.T, q.T)
print("Covariance:")
print()
print(cov1)



Matrix Multiplication:

[[16 19]
 [26 31]]
Covariance:

[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


h) For the matrices:

x = np.array([[2, 3, 4], [3, 2, 9]]);

y = np.array([[1, 5, 0], [5, 10, 3]]),

find inner, outer and cartesian product?

In [ ]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
inner=np.inner(x,y)
print("Inner Product:\n",inner)
print()
outer=np.outer(x,y)
print("Outer Product:\n",outer)
print()
from itertools import product
cartesian=np.array(list(product(x.flatten(),y.flatten())))
print("Cartesian Product:\n",cartesian)

Inner Product:
 [[17 52]
 [13 62]]

Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row



(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

Find floor, ceiling
and truncated value, rounded values

In [ ]:
import numpy as np
array=np.array([[1,-2,3],[-4,5,-6]])
abs_array=np.abs(array)
print("Absolute Values:\n",abs_array)
print()

flat=array.flatten()
print("Flattened Percentiles:")
print("25th:",np.percentile(flat,25))
print("50th:",np.percentile(flat,50))  # median
print("75th:",np.percentile(flat,75))
print()

print("Column-wise Percentiles:")
print("25th:",np.percentile(array,25,axis=0))
print("50th:",np.percentile(array,50,axis=0))
print("75th:",np.percentile(array,75,axis=0))
print()

print("Row-wise Percentiles:")
print("25th:", np.percentile(array,25,axis=1))
print("50th:", np.percentile(array,50,axis=1))
print("75th:", np.percentile(array,75,axis=1))
print()

print("Mean (Flattened):",np.mean(flat))
print("Median (Flattened):",np.median(flat))
print("Std Dev (Flattened):",np.std(flat))
print()

print("Mean (Column-wise):",np.mean(array,axis=0))
print("Median (Column-wise):",np.median(array,axis=0))
print("Std Dev (Column-wise):",np.std(array,axis=0))
print()

print("Mean (Row-wise):",np.mean(array,axis=1))
print("Median (Row-wise):",np.median(array,axis=1))
print("Std Dev (Row-wise):",np.std(array,axis=1))


Absolute Values:
 [[1 2 3]
 [4 5 6]]

Flattened Percentiles:
25th: -3.5
50th: -0.5
75th: 2.5

Column-wise Percentiles:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]

Row-wise Percentiles:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]

Mean (Flattened): -0.5
Median (Flattened): -0.5
Std Dev (Flattened): 3.8622100754188224

Mean (Column-wise): [-1.5  1.5 -1.5]
Median (Column-wise): [-1.5  1.5 -1.5]
Std Dev (Column-wise): [2.5 3.5 4.5]

Mean (Row-wise): [ 0.66666667 -1.66666667]
Median (Row-wise): [ 1. -4.]
Std Dev (Row-wise): [2.05480467 4.78423336]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements



(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print()
print("Sorted Indices:", np.argsort(array))
print()
print("4 Smallest:", np.sort(array)[:4])
print()
print("5 Largest:", np.sort(array)[-5:])
print()
print()


array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Integer Elements:", ints)
print()
print("Float Elements:", floats)
print()

Sorted: [ 10  16  16  52  54  62 453]

Sorted Indices: [0 3 4 1 5 2 6]

4 Smallest: [10 16 16 52]

5 Largest: [ 16  52  54  62 453]


Integer Elements: [1. 2. 3. 2.]

Float Elements: [1.2 2.2]



Q4

a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

b) Load the saved file into jupyter notebook

In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img=Image.open(path)
    arr=np.array(img)
    if len(arr.shape)==2:
        np.savetxt("grayscale_image.txt",arr,fmt='%d')
    else:
        np.savetxt("rgb_image.txt",arr.reshape(-1,arr.shape[2]),fmt='%d')


gray = np.loadtxt("grayscale_image.txt", dtype=int)
rgb = np.loadtxt("rgb_image.txt", dtype=int)


FileNotFoundError: grayscale_image.txt not found.